# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install IPFS
        uses: ibnesayeed/setup-ipfs@c779340c110024feeb46579fef211c89332caf85
        with:
          ipfs_version: ${{vars.IPFS_VERSION}}
          run_daemon: true

      - name: Swarm peering add to our IPFS Servers
        run: |
          ipfs swarm peering add "${{vars.FLUORINE_MULTIADDRESS}}"
          ipfs swarm peering add "${{vars.CERIUM_MULTIADDRESS}}"
          ipfs swarm peering add "${{vars.BISMUTH_MULTIADDRESS}}"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install all dependencies
        run: uv sync --extra dev --extra testing

      - name: Run pytest with coverage
        run: uv run pytest --cov=src tests/ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run nox
        run: |
          uv run nox
